%% OTIMIZACAO ALIMENTAR:
%  FREDERICO CASARA ANTONIAZZI - 29/10/2024

%  CODIGO DESENVOLVIDO PARA PERMITIR A SELECAO DE PRODUTOS ALIMENTARES
%  BASEADO EM RESTRICOES DE PROTEINAS, CARBOIDRATOS E OUTROS ATRAVES DO
%  ESTUDO DE PRECOS DE DIFERENTES MERCADOS NA CIDADE DE CAXIAS DO SUL

%% ORGANIZACAO BASICA:

clc;
clear;
close all;

format short;

%% INICIALIZANDO AS TABELAS DE MERCADO COM PRODUTOS:





